/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estado del servicio */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/resolver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolver un problema paso a paso
         * @description Devuelve todas las operaciones del desarrollo y el resultado. No guarda nada.
         */
        post: operations["resolver_api_v1_resolver_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/importar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Importar un archivo .simplex.json
         * @description Valida el archivo y vuelve a resolver el problema que contiene.
         */
        post: operations["importar_api_v1_importar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exportar/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exportar el desarrollo completo a PDF */
        post: operations["exportar_pdf_api_v1_exportar_pdf_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Guardar un problema y obtener su enlace */
        post: operations["guardar_problema_api_v1_problemas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problemas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Abrir un problema guardado */
        get: operations["obtener_problema_api_v1_problemas__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ejemplos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problemas precargados */
        get: operations["obtener_ejemplos_api_v1_ejemplos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ArchivoSimplex
         * @description Contenido de un archivo .simplex.json exportado o de un ejemplo precargado.
         *
         *     Al importar solo se usa `problema`: el backend vuelve a resolver y no confía en `solucion`.
         */
        ArchivoSimplex: {
            /**
             * Formato
             * @default simplex-paso-a-paso
             * @constant
             */
            formato: "simplex-paso-a-paso";
            /**
             * Version Formato
             * @default 1
             * @constant
             */
            version_formato: 1;
            /**
             * Titulo
             * @default Problema sin título
             */
            titulo: string;
            /** Descripcion */
            descripcion?: string | null;
            /** Exportado En */
            exportado_en?: string | null;
            problema: components["schemas"]["Problema"];
            solucion?: components["schemas"]["RespuestaResolver"] | null;
        };
        /** Clasificacion */
        Clasificacion: {
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "normal" | "extendido";
            /**
             * Motivo
             * @example Hay restricciones ≥ y =: se usarán Dos Fases
             */
            motivo: string;
        };
        /** Ejemplo */
        Ejemplo: {
            /**
             * Id
             * @example profesor-max
             */
            id: string;
            /** Titulo */
            titulo: string;
            /** Descripcion */
            descripcion?: string | null;
            problema: components["schemas"]["Problema"];
        };
        /**
         * Estado
         * @enum {string}
         */
        Estado: "optimo" | "multiples_optimos" | "no_acotado" | "infactible";
        /** GuardarProblema */
        GuardarProblema: {
            /**
             * Titulo
             * @default Problema sin título
             */
            titulo: string;
            problema: components["schemas"]["Problema"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OperacionFila
         * @description Operación de Gauss-Jordan sobre una fila, valor por valor.
         */
        OperacionFila: {
            /** Fila */
            fila: string;
            /**
             * Latex
             * @example R_2' = -20\,R_3' + R_2
             */
            latex: string;
            /** Antes */
            antes: string[];
            /**
             * Suma
             * @description Término que se suma, por ejemplo −20·R3'
             */
            suma?: string[] | null;
            /** Despues */
            despues: string[];
        };
        /**
         * Paso
         * @description Una operación atómica del desarrollo. El puntero del frontend avanza de a uno.
         */
        Paso: {
            /** Indice */
            indice: number;
            /** Fase */
            fase?: (1 | 2) | null;
            /** Iteracion */
            iteracion?: number | null;
            tipo: components["schemas"]["TipoPaso"];
            /** Titulo */
            titulo: string;
            /** Texto */
            texto: string;
            /** Latex */
            latex?: string | null;
            /** Razones */
            razones?: components["schemas"]["RazonFila"][] | null;
            operacion?: components["schemas"]["OperacionFila"] | null;
            resaltar?: components["schemas"]["Resaltado"];
            /** @description Cómo queda la tabla después de aplicar el paso */
            tabla?: components["schemas"]["TablaSimplex"] | null;
        };
        /**
         * Problema
         * @description Modelo de programación lineal tal como lo escribe el usuario.
         * @example {
         *       "coef_objetivo": [
         *         "10",
         *         "15"
         *       ],
         *       "objetivo": "max",
         *       "restricciones": [
         *         {
         *           "coeficientes": [
         *             "1",
         *             ""
         *           ],
         *           "lado_derecho": "400",
         *           "signo": "<="
         *         },
         *         {
         *           "coeficientes": [
         *             "15",
         *             "20"
         *           ],
         *           "lado_derecho": "500",
         *           "signo": ">="
         *         },
         *         {
         *           "coeficientes": [
         *             "",
         *             "8"
         *           ],
         *           "lado_derecho": "100",
         *           "signo": "="
         *         }
         *       ]
         *     }
         */
        Problema: {
            /**
             * Objetivo
             * @enum {string}
             */
            objetivo: "max" | "min";
            /** Coef Objetivo */
            coef_objetivo: string[];
            /** Restricciones */
            restricciones: components["schemas"]["Restriccion"][];
        };
        /** ProblemaGuardado */
        ProblemaGuardado: {
            /**
             * Slug
             * @description Identificador del enlace para compartir
             */
            slug: string;
            /** Titulo */
            titulo: string;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            problema: components["schemas"]["Problema"];
            solucion: components["schemas"]["RespuestaResolver"];
        };
        /**
         * RazonFila
         * @description Una línea de la prueba de razón mínima.
         */
        RazonFila: {
            /** Fila */
            fila: string;
            /** Participa */
            participa: boolean;
            /**
             * Calculo
             * @example 500 ÷ 20
             */
            calculo?: string | null;
            /** Resultado */
            resultado?: string | null;
            /**
             * Motivo
             * @example división entre 0: no se considera
             */
            motivo?: string | null;
            /**
             * Menor
             * @default false
             */
            menor: boolean;
        };
        /**
         * Resaltado
         * @description Qué partes de la tabla se destacan en el paso.
         */
        Resaltado: {
            /** Columnas */
            columnas?: string[];
            /** Filas */
            filas?: string[];
            /**
             * Celdas
             * @description Pares (fila, columna), por ejemplo el pivote
             */
            celdas?: [
                string,
                string
            ][];
        };
        /**
         * RespuestaResolver
         * @description Desarrollo completo de un problema: todos los pasos y el resultado.
         */
        RespuestaResolver: {
            /**
             * Version Formato
             * @default 1
             * @constant
             */
            version_formato: 1;
            problema: components["schemas"]["Problema"];
            clasificacion: components["schemas"]["Clasificacion"];
            estado: components["schemas"]["Estado"];
            /** Pasos */
            pasos: components["schemas"]["Paso"][];
            /** @description Vacío si el problema es infactible o no acotado */
            resultado?: components["schemas"]["ResultadoFinal"] | null;
        };
        /** Restriccion */
        Restriccion: {
            /** Coeficientes */
            coeficientes: string[];
            /**
             * Signo
             * @enum {string}
             */
            signo: "<=" | ">=" | "=";
            /**
             * Lado Derecho
             * @description Número exacto: entero, decimal o fracción. Vacío equivale a 0.
             * @example 3/4
             * @example -2
             * @example 0.5
             */
            lado_derecho: string;
        };
        /** ResultadoFinal */
        ResultadoFinal: {
            /**
             * Variables
             * @description Variables de decisión: x1, x2…
             */
            variables: {
                [key: string]: string;
            };
            /**
             * Holguras
             * @description Holguras y excesos; sin artificiales
             */
            holguras: {
                [key: string]: string;
            };
            /**
             * Z
             * @description Número exacto: entero, decimal o fracción. Vacío equivale a 0.
             * @example 3/4
             * @example -2
             * @example 0.5
             */
            z: string;
        };
        /**
         * TablaSimplex
         * @description Estado de la tabla simplex en un momento del desarrollo.
         */
        TablaSimplex: {
            /**
             * Columnas
             * @description Variables en orden: x1, x2, S1, S2, A1…
             */
            columnas: string[];
            /**
             * Cj
             * @description Coeficiente de cada columna en el objetivo de la fase
             */
            cj: string[];
            /**
             * Base
             * @description Variable básica de cada fila
             */
            base: string[];
            /**
             * Cb
             * @description Cj de la variable básica de cada fila
             */
            cb: string[];
            /**
             * B
             * @description Lado derecho de cada fila
             */
            b: string[];
            /**
             * Matriz
             * @description Coeficientes: una lista por fila
             */
            matriz: string[][];
            /**
             * Nombre Objetivo
             * @description W en Fase 1, Z en Fase 2
             * @enum {string}
             */
            nombre_objetivo: "Z" | "W";
            /**
             * Fila Z
             * @description Zj − Cj de cada columna
             */
            fila_z: string[];
            /**
             * Valor Z
             * @description Valor actual de Z o W
             * @example 3/4
             * @example -2
             * @example 0.5
             */
            valor_z: string;
        };
        /**
         * TipoPaso
         * @description Cada operación que el modo paso a paso muestra por separado.
         * @enum {string}
         */
        TipoPaso: "modelo_original" | "clasificacion" | "forma_extendida" | "tabla_inicial" | "fila_z_inicial" | "anular_basica_en_z" | "prueba_optimalidad" | "variable_entra" | "prueba_razon" | "variable_sale" | "fila_pivote" | "operacion_fila" | "fila_sin_cambio" | "operacion_fila_z" | "comprobacion_zj" | "solucion_actual" | "fin_fase_1" | "inicio_fase_2" | "lectura_resultado" | "caso_especial";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    resolver_api_v1_resolver_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Problema"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaResolver"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Motor pendiente (Sprint 1) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    importar_api_v1_importar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArchivoSimplex"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RespuestaResolver"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Pendiente (Sprint 3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    exportar_pdf_api_v1_exportar_pdf_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Problema"];
            };
        };
        responses: {
            /** @description Archivo PDF */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Pendiente (Sprint 3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    guardar_problema_api_v1_problemas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardarProblema"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaGuardado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Pendiente (Sprint 3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No hay base de datos configurada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtener_problema_api_v1_problemas__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemaGuardado"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Pendiente (Sprint 3) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No hay base de datos configurada */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    obtener_ejemplos_api_v1_ejemplos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ejemplo"][];
                };
            };
        };
    };
}
